    public class Achievements
    {
        public UnlockDust UnlockDust { get; set; }
        public CommonDust CommonDust { get; set; }
        public Dirt Dirt { get; set; }
        public SandDust SandDust { get; set; }
        public GrassPollen GrassPollen { get; set; }
        public RoadDust RoadDust { get; set; }
        public Sawdust Sawdust { get; set; }
        public CoalDust CoalDust { get; set; }
        public MoonDust MoonDust { get; set; }
        public MarsDust MarsDust { get; set; }
        public AsteroidDust AsteroidDust { get; set; }
        public StarDust StarDust { get; set; }
        public CosmicDust CosmicDust { get; set; }
        public RocketDust RocketDust { get; set; }
        public UnlockFirstVacuum UnlockFirstVacuum { get; set; }
        public UnlockFirstAVA UnlockFirstAVA { get; set; }
        public UnlockFirstLocation UnlockFirstLocation { get; set; }
        public ClickDiscord ClickDiscord { get; set; }
        public ClickReddit ClickReddit { get; set; }
        public GameTime GameTime { get; set; }
        public RobotCharacter RobotCharacter { get; set; }
        public SupporterShopOpen SupporterShopOpen { get; set; }
        public RideAnAVA RideAnAVA { get; set; }
        public FirstPrestige FirstPrestige { get; set; }
        public Prestiges Prestiges { get; set; }
        public UnlockManagers UnlockManagers { get; set; }
        public AcademyHire AcademyHire { get; set; }
        public MergeManagers MergeManagers { get; set; }
        public SixStarManager SixStarManager { get; set; }
        public OwnManagers OwnManagers { get; set; }
        public OwnEnthusiast OwnEnthusiast { get; set; }
        public OwnExpert OwnExpert { get; set; }
        public BuyTokens BuyTokens { get; set; }
        public OwnTenAvas OwnTenAvas { get; set; }
        public MaxedAvas MaxedAvas { get; set; }
        public ManagerAllLocations ManagerAllLocations { get; set; }
        public OpenCommonChests OpenCommonChests { get; set; }
        public OpenGoldenChest OpenGoldenChest { get; set; }
        public ExceedChestStorageCapacity ExceedChestStorageCapacity { get; set; }
        public UnlockJunk UnlockJunk { get; set; }
        public CollectJunk CollectJunk { get; set; }
        public StoreJunk StoreJunk { get; set; }
        public UnlockOfflineJunk UnlockOfflineJunk { get; set; }
        public UnlockBoosts UnlockBoosts { get; set; }
        public CraftBoosts CraftBoosts { get; set; }
        public Have3BoostsActive Have3BoostsActive { get; set; }
        public Have5BoostsActive Have5BoostsActive { get; set; }
        public UseBoosts UseBoosts { get; set; }
    }
