    public class ShopItems
    {
        public UnlockNextDust UnlockNextDust { get; set; }
        public Carpet Carpet { get; set; }
        public ParticleSize ParticleSize { get; set; }
        public SpawnRate SpawnRate { get; set; }
        public LumpSpawning LumpSpawning { get; set; }
        public AVA AVA { get; set; }
        public Size Size { get; set; }
        public Speed Speed { get; set; }
        public Suction Suction { get; set; }
        public Angle Angle { get; set; }
        public Objects Objects { get; set; }
        public BeginnerVacuum BeginnerVacuum { get; set; }
        public BasicStick BasicStick { get; set; }
        public AdvancedStick AdvancedStick { get; set; }
        public BasicUpright BasicUpright { get; set; }
        public AdvancedUpright AdvancedUpright { get; set; }
        public BasicBackpack BasicBackpack { get; set; }
        public AdvancedBackpack AdvancedBackpack { get; set; }
        public MegaAVA MegaAVA { get; set; }
        public BasicPushableSweeper BasicPushableSweeper { get; set; }
        public AdvancedPushableSweeper AdvancedPushableSweeper { get; set; }
        public Locations Locations { get; set; }
        public Manager Managers { get; set; }
        public ShopAutomation ShopAutomation { get; set; }
        public JunkItems JunkItems { get; set; }
        public OmniJunk OmniJunk { get; set; }
        public Boosts Boosts { get; set; }
        public LumpSellMultiplier LumpSellMultiplier { get; set; }
        public DustShopDiscount DustShopDiscount { get; set; }
        public DustBuildup DustBuildup { get; set; }
        public PrestigeCoinMultiplier PrestigeCoinMultiplier { get; set; }
        public CommonDust CommonDust { get; set; }
        public Dirt Dirt { get; set; }
        public SandDust SandDust { get; set; }
        public GrassPollen GrassPollen { get; set; }
        public RoadDust RoadDust { get; set; }
        public Sawdust Sawdust { get; set; }
        public CoalDust CoalDust { get; set; }
        public RocketDust RocketDust { get; set; }
        public MoonDust MoonDust { get; set; }
        public Home Home { get; set; }
        public Neighbour Neighbour { get; set; }
        public Lawn Lawn { get; set; }
        public Road Road { get; set; }
        public Sawmill Sawmill { get; set; }
        public Mine Mine { get; set; }
        public Spaceport Spaceport { get; set; }
        public Moon Moon { get; set; }
        public KeepVacuums KeepVacuums { get; set; }
        public ExtraManagerSlot ExtraManagerSlot { get; set; }
        public MovementSpeed MovementSpeed { get; set; }
        public ParticleMultiplier ParticleMultiplier { get; set; }
        public OfflineTime OfflineTime { get; set; }
        public InfinityCapsule1 InfinityCapsule1 { get; set; }
        public InfinityCapsule2 InfinityCapsule2 { get; set; }
        public InfinityCapsule3 InfinityCapsule3 { get; set; }
        public InfinityCapsule4 InfinityCapsule4 { get; set; }
        public ChestBuildup ChestBuildup { get; set; }
        public OfflineChestsEfficiency OfflineChestsEfficiency { get; set; }
        public ChestStorageCommon ChestStorageCommon { get; set; }
        public AVACollectCommon AVACollectCommon { get; set; }
        public OfflineChestsCommon OfflineChestsCommon { get; set; }
        public ChestStorageGolden ChestStorageGolden { get; set; }
        public AVACollectGolden AVACollectGolden { get; set; }
        public GoldenProbability GoldenProbability { get; set; }
        public OfflineChestsGolden OfflineChestsGolden { get; set; }
        public AutoBuyerSpeed AutoBuyerSpeed { get; set; }
        public AvaAutoBuyer AvaAutoBuyer { get; set; }
        public JunkCapacity JunkCapacity { get; set; }
        public JunkSpawnRate JunkSpawnRate { get; set; }
        public JunkBuildup JunkBuildup { get; set; }
        public AvaCollectJunk AvaCollectJunk { get; set; }
        public OfflineJunk OfflineJunk { get; set; }
        public OfflineJunkEfficiency OfflineJunkEfficiency { get; set; }
        public ParticleSpawnRateBoost ParticleSpawnRateBoost { get; set; }
        public LumpSpawnRateBoost LumpSpawnRateBoost { get; set; }
        public AvaReinforcements AvaReinforcements { get; set; }
        public AvaSpeedBoost AvaSpeedBoost { get; set; }
        public JunkSpawnRateBoost JunkSpawnRateBoost { get; set; }
        public ChestSpawnRateBoost ChestSpawnRateBoost { get; set; }
        public Prestige Prestige { get; set; }
    }
